{% set name = "prefect" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b068d6446ab7c227f703e4670862274ce3eea14e2925a41eae48c184fdf32ce2

build:
  number: 1
  script: {{ PYTHON }} -m pip install --no-deps -vv .
  entry_points:
    - prefect = prefect.cli:cli

requirements:
  host:
    - python
    - pip
  run:
    - python
    - aiofiles >=0.7.0
    - aiohttp >=3.8.1
    - aiosqlite >=0.17.0 
    - alembic >=1.7.5
    - anyio >=3.4.0
    - asgi-lifespan >=1.0
    - asyncpg >=0.23
    - click >=8.0, < 8.2
    - cloudpickle >=2.0
    - coolname >=1.0.4
    - croniter >=1.0.12
    - cryptography >=36.0.1
    - docker-py >=4.0
    - fastapi >=0.70
    - fsspec >=2022.5.0
    - griffe >=0.20.0, <0.22.0 
    - httpx >=0.22
    - importlib_metadata >=4.4  # [py<=39]
    - jsonpatch >=1.32
    - python-kubernetes >=24.2.0
    - packaging >=21.3
    - pendulum >=2.1.2
    - pickle5 >=0.0.11  # [py<38]
    - pydantic >=1.8.2
    - python-slugify >=5.0
    - pytz >=2021.1
    - pyyaml >=5.4.1
    - readchar >=3.0.5
    - rich >=11.0
    - slack-sdk >=3.15.1
    - sqlalchemy[asyncio] >=1.4.20,!= 1.4.33
    - toml >=0.10.0
    - typer >=0.4.1
    - typing_extensions >=4.0.1
    - uvicorn  >=0.14.0

test:
  imports:
    - prefect
    - prefect.flows
    - prefect.blocks
    - prefect.tasks
    - prefect.engine
    - prefect.cli
  requires:
    - pip
about:
  home: https://github.com/PrefectHQ/prefect
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'The Prefect Core automation engine '
  description: |
    Prefect is a workflow management system, designed for modern infrastructure
    and powered by the open-source Prefect Core workflow engine.
    Users organize `Tasks` into `Flows`, and Prefect takes care of the rest.
  doc_url: https://docs.prefect.io/

extra:
  recipe-maintainers:
    - Sahiler
    - cicdw
    - madkinsz
