{% set name = "prefect" %}
{% set version = "3.6.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 664c33ccab045ae1faa2cf6a01d39bd6679fabe8f815a51025f6160d387e6a21

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - prefect = prefect.cli:app

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - versioningit
  run:
    - python >={{ python_min }}
    - aiosqlite >=0.17.0,<1.0.0
    - alembic >=1.7.5,<2.0.0
    - anyio >=4.4.0,<5.0.0
    - apprise >=1.1.0,<2.0.0
    - asgi-lifespan >=1.0,<3.0
    - asyncpg >=0.23,<1.0.0
    - cachetools >=5.3,<7.0
    - click >=8.0,<9.0
    - cloudpickle >=2.0,<4.0
    - coolname >=1.0.4,<3.0.0
    - croniter >=1.0.12,<5.0.0
    - cryptography >=36.0.1
    - dateparser >=1.1.1,<2.0.0
    - docker-py >=4.0,<8.0
    - exceptiongroup >=1.0.0
    - fastapi >=0.111.0,<1.0.0
    - fsspec >=2022.5.0
    - griffe >=0.49.0,<2.0.0
    - httpcore >=1.0.5,<2.0.0
    - httpx >=0.23,!=0.23.2
    - humanize >=4.9.0,<5.0.0
    - importlib-metadata >=4.4
    - jinja2 >=3.1.6,<4.0.0
    - jinja2-humanize-extension >=0.4.0
    - jsonpatch >=1.32,<2.0
    - jsonschema >=4.18.0,<5.0.0
    - opentelemetry-api >=1.27.0,<2.0
    - orjson >=3.7,<4.0
    - packaging >=21.3,<25.1
    - pathspec >=0.8.0
    - pendulum >=3.0.0,<4
    - pluggy >=1.6.0
    - prometheus_client >=0.20.0
    - pydantic >=2.9,<3.0.0,!=2.10.0,!=2.11.0,!=2.11.1,!=2.11.2,!=2.11.3,!=2.11.4
    - pydantic-core >=2.12.0,<3.0.0
    - pydantic-extra-types >=2.8.2,<3.0.0
    - pydantic-settings >2.2.1,<3.0.0,!=2.9.0
    - pydocket >0.13.3
    - python-dateutil >=2.8.2,<3.0.0
    - python-graphviz >=0.20.1
    - python-slugify >=5.0,<9.0
    - python-tzdata
    - python-socks[asyncio] >=2.5.3,<3.0
    - pytz >=2021.1,<2025
    - pyyaml >=5.4.1,<7.0.0
    - readchar >=4.0.0,<5.0.0
    - rfc3339-validator >=0.1.4,<0.2.0
    - rich >=11.0,<14.0
    - ruamel.yaml >=0.17.0
    - semver >=3.0.4
    - sniffio >=1.3.0,<2.0.0
    - sqlalchemy[asyncio] >=2.0,<3.0.0
    - toml >=0.10.0
    - typer >=0.16.0,<0.20.0
    - typing_extensions >=4.5.0,<5.0.0
    - ujson >=5.8.0,<6.0.0
    - python-uv >=0.6.0
    - uvicorn >=0.14.0,!=0.29.0
    - websockets >=13.4,<16.0
    - whenever >=0.7.3,<0.9.0

test:
  imports:
    - prefect
    - prefect.cli
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    # Check that the entrypoint is configured
    - prefect --help
    # Check that the long-form version command works (this uses a database and client)
    - prefect version
    # Check that the version is correct
    - sh -c '[ "$(prefect --version)" = "{{ version }}" ]'

about:
  home: https://github.com/PrefectHQ/prefect
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'The Prefect Core automation engine '
  description: |
    Prefect is a workflow management system, designed for modern infrastructure
    and powered by the open-source Prefect Core workflow engine.
    Users organize `Tasks` into `Flows`, and Prefect takes care of the rest.
  doc_url: https://docs.prefect.io/

extra:
  recipe-maintainers:
    - zzstoatzz
    - cicdw
    - desertaxle
