{% set name = "prefect" %}
{% set version = "2.20.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ad124457dda96a60d1e6c3d038abaf75d2d3193177d8314cda001d82e10d7168

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps -vv .
  entry_points:
    - prefect = prefect.cli:app

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - aiosqlite >=0.17.0, <1.0.0
    - alembic >=1.7.5, <2.0.0
    - anyio >=4.4.0, <4.6.1
    - apprise >=1.1.0, <2.0.0
    - asgi-lifespan >=1.0, <3.0
    - asyncpg >=0.23, <0.30.0
    - click >=8.0, <8.2
    - cloudpickle >=2.0, <4.0
    - coolname >=1.0.4, <3.0.0
    - croniter >=1.0.12, <6.0.0
    - cryptography >=36.0.1
    - dateparser >=1.1.1, <2.0.0
    - exceptiongroup >=1.2.1
    - docker-py >=4.0, <8.0
    - fsspec >=2022.5.0
    - griffe >=0.49.0, <2.0.0
    - httpcore >=0.15.0, <2.0.0
    - httpx >=0.23, !=0.23.2
    - importlib-metadata >=4.4
    - importlib_resources >=6.1.3, <6.5.0
    - jsonpatch >=1.32, <2.0
    - jsonschema >=3.2.0, <5.0.0
    - jinja2 >=3.0.0, <4.0.0
    - jinja2-humanize-extension >=0.4.0
    - orjson >=3.7, <4.0
    - pathspec >=0.8.0
    - python-graphviz >=0.20.1
    - python-kubernetes >=24.2.0, <32.0.0
    - python-multipart >=0.0.7
    - packaging >=21.3, <24.3
    - pendulum >=2.1.2, <3.0.0
    - pydantic >=1.10.0, !=1.10.14, !=2.0.0, !=2.0.1, !=2.1.0, <3.0.0
    - pydantic-core >=2.17.0, <3.0.0
    - python-dateutil >=2.8.2, <3.0.0
    - python-slugify >=5.0, <9.0
    - pytz >=2021.1, <2024
    - pyyaml >=5.4.1, <7.0.0
    - readchar >=4.0.0, <5.0.0
    - rich >=11.0, <14.0
    - ruamel.yaml >=0.17.0
    - sniffio >=1.3.0, <2.0.0
    - sqlalchemy[asyncio] >=1.4.22, != 1.4.33, <2.0.36
    - starlette >=0.27.0, <0.28.0
    - toml >=0.10.0
    - typer >=0.12.0, != 0.12.2, <0.16.0
    - typing_extensions >=4.5.0, <5.0.0
    - ujson >=5.8.0, <6.0.0
    - uvicorn >=0.14.0, != 0.29.0
    - websockets >=10.4, <14.0
test:
  imports:
    - prefect
    - prefect.cli
  requires:
    - pip
  commands:
    # `pip check` fails on `readchar` which has a different identifier when provided by conda
    # A `--ignore` flag is in progress at https://github.com/pypa/pip/pull/11159 which will
    # allow us to enable this check again while excluding readchar
    # - pip check
    # Check that the entrypoint is configured
    - prefect --help
    # Check that the long-form version command works (this uses a database and client)
    - prefect version
    # Check that the version is correct
    - sh -c '[ "$(prefect --version)" = "{{ version }}" ]'

about:
  home: https://github.com/PrefectHQ/prefect
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'The Prefect Core automation engine '
  description: |
    Prefect is a workflow management system, designed for modern infrastructure
    and powered by the open-source Prefect Core workflow engine.
    Users organize `Tasks` into `Flows`, and Prefect takes care of the rest.
  doc_url: https://docs.prefect.io/

extra:
  recipe-maintainers:
    - zzstoatzz
    - cicdw
    - desertaxle
