{% set sdata = load_setup_py_data() %}
{% set name = "prefect" %}
{% set version = "0.13.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 063566bd3b1043236d43cdc1a91935acaec3b46e4f1a46937f61d3d33613525a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps -vv .
  entry_points:
    - prefect = prefect.cli:cli

requirements:
  host:
    - python {{ sdata['python_requires'] }}
    - pip
  run:
    - python {{ sdata['python_requires'] }}
    {% for dep in sdata['install_requires'] %}
    - {{ dep|replace(">= ", ">=") }}
    {% endfor %}

test:
  imports:
    - prefect
    - prefect.triggers
    - prefect.schedules
    - prefect.tasks.shell
    - prefect.tasks.control_flow
    - prefect.tasks.github
  requires:
    {% for dep in sdata['extras_require']['test'] %}
    - {{ dep }}
    {% endfor %}

output:
  # The main build
  - name: prefect
  # The development build
  - name: prefect-dev
    requirements:
      run:
        - prefect-test =={{ version }}
        {% for dep in sdata['extras_require']['dev'] %}
        - {{ dep }}
        {% endfor %}
  # Cloud specific builds
  - name: prefect-aws
    requirements:
      run:
        - prefect =={{ version }}
        {% for dep in sdata['extras_require']['aws'] %}
        - {{ dep }}
        {% endfor %}
  - name: prefect-azure
    requirements:
      run:
        - prefect =={{ version }}
        {% for dep in sdata['extras_require']['azure'] %}
        - {{ dep }}
        {% endfor %}
  - name: prefect-gcp
    requirements:
      run:
        - prefect =={{ version }}
        {% for dep in sdata['extras_require']['gcp'] %}
        - {{ dep }}
        {% endfor %}
  - name: prefect-kubernetes
    requirements:
      run:
        - prefect =={{ version }}
        {% for dep in sdata['extras_require']['kubernetes'] %}
        - {{ dep }}
        {% endfor %}


about:
  home: https://github.com/PrefectHQ/prefect
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'The Prefect Core automation engine '
  description: |
    Prefect is a new workflow management system, designed for modern
    infrastructure and powered by the open-source Prefect Core workflow engine.
    Users organize `Tasks` into `Flows`, and Prefect takes care of the rest.
  doc_url: https://docs.prefect.io/

extra:
  recipe-maintainers:
    - cicdw
    - jcrist
    - joshmeek
    - dhirschfeld
    - rzillman
