{% set name = "prefect" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a9b9210abbe2f657400bd4f070e3c6bb0b9d331559960cdc8214aebfd6098084

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps -vv .
  entry_points:
    - prefect = prefect.cli:cli

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - click >=7.0
    - cloudpickle >=1.3.0
    - croniter >=0.3.24,<1.0
    - dask-core >=2.17.0
    - distributed >=2.17.0
    - docker-py >=3.4.1
    - importlib_resources >=3.0
    - marshmallow >=3.0.0b19
    - marshmallow-oneofschema >=2.0.0b2
    - mypy_extensions >=0.4.0
    - packaging >=20.0
    - pendulum >=2.0.4
    - python-dateutil >2.7.3
    - pyyaml >=3.13
    - python-box >=5.1.0
    - python-slugify >=1.2.6
    - pytz >=2018.7
    - requests >=2.20
    - tabulate >=0.8.0
    - toml >=0.9.4
    - urllib3 >=1.24.3

test:
  imports:
    - prefect
    - prefect.triggers
    - prefect.schedules
    - prefect.tasks.shell
    - prefect.tasks.control_flow
    - prefect.tasks.github

about:
  home: https://github.com/PrefectHQ/prefect
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'The Prefect Core automation engine '
  description: |
    Prefect is a workflow management system, designed for modern infrastructure
    and powered by the open-source Prefect Core workflow engine.
    Users organize `Tasks` into `Flows`, and Prefect takes care of the rest.
  doc_url: https://docs.prefect.io/

extra:
  recipe-maintainers:
    - cicdw
    - madkinsz
