{% set name = "prefect" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c2f25b0e39a37ee1c01fc19ef08e08e9f00dbc8383edca2b5879f0091730aa32

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install --no-deps -vv .
  entry_points:
    - prefect = prefect.cli:app

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - aiofiles >=0.7.0
    - aiohttp >=3.8.1
    - aiosqlite >=0.17.0
    - alembic >=1.7.5
    - anyio >=3.4.0
    - asgi-lifespan >=1.0
    - asyncpg >=0.23
    - click >=8.0, < 8.2
    - cloudpickle >=2.0
    - coolname >=1.0.4
    - croniter >=1.0.12
    - cryptography >=36.0.1
    - docker-py >=4.0
    - fastapi >=0.70
    - fsspec >=2022.5.0
    - griffe >=0.20.0, <0.22.0
    - httpx >=0.22
    - importlib_metadata >=4.4
    - jsonpatch >=1.32
    - pathspec >=0.8.0
    - python-kubernetes >=24.2.0
    - packaging >=21.3
    - pendulum >=2.1.2
    - pydantic >=1.8.2
    - python-slugify >=5.0
    - pytz >=2021.1
    - pyyaml >=5.4.1
    - readchar >=3.0.5
    - rich >=11.0
    - slack-sdk >=3.15.1
    - sqlalchemy[asyncio] >=1.4.20,!= 1.4.33
    - toml >=0.10.0
    - typer >=0.4.1
    - typing_extensions >=4.0.1
    - uvicorn  >=0.14.0

test:
  imports:
    - prefect
    - prefect.cli
  requires:
    - pip
  commands:
    # `pip check` fails on `readchar` which has a different identifier when provided by conda
    # A `--ignore` flag is in progress at https://github.com/pypa/pip/pull/11159 which will
    # allow us to enable this check again while excluding readchar
    # - pip check
    # Check that the entrypoint is configured
    - prefect --help
    # Check that the long-form version command works (this uses a database and client)
    - prefect version
    # Check that the version is correct
    - sh -c '[ "$(prefect --version)" = "{{ version }}" ]'

about:
  home: https://github.com/PrefectHQ/prefect
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'The Prefect Core automation engine '
  description: |
    Prefect is a workflow management system, designed for modern infrastructure
    and powered by the open-source Prefect Core workflow engine.
    Users organize `Tasks` into `Flows`, and Prefect takes care of the rest.
  doc_url: https://docs.prefect.io/

extra:
  recipe-maintainers:
    - Sahiler
    - cicdw
    - madkinsz
